version: '3.3'

networks:
  default:
  servicebus:

services:

  staging-deps:
    image: microservice
    environment:
      - NODE_ENV=production
      - PORT=3000
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=servicebus*,register-handlers*
    networks:
      - servicebus
      - default
    depends_on:
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.6-management
    hostname: rabbitmq
    networks:
      - servicebus
    ports:
      - 15672:15672

  redis:
    image: redis
    networks:
      - servicebus

  # reinstall dev deps to get testing tools and run staging tests
  staging:
    image: node:10
    volumes:
      - ..:/usr/src/service
    working_dir: /usr/src/service
    networks:
      - servicebus
      - default
    environment:
      - apiUrl=http://staging-deps:3000
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=$DEBUG
    command: npm run test:staging
